# Get baseline
FROM quay.io/pypa/manylinux2014_x86_64

# Add Oracle repo
RUN echo -e "\
[ol7_software_collections]\n\
name=Software Collection packages for Oracle Linux 7 (\$basearch)\n\
baseurl=http://yum.oracle.com/repo/OracleLinux/OL7/SoftwareCollections/\$basearch/\n\
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle\n\
gpgcheck=1\n\
enabled=1" > /etc/yum.repos.d/OracleLinux7.repo

# Update Key
RUN curl https://yum.oracle.com/RPM-GPG-KEY-oracle-ol7 --output /etc/pki/rpm-gpg/RPM-GPG-KEY-oracle && \
    gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-oracle

# Update baseline
RUN yum -y update && \
    yum -y upgrade && \
    yum install -y openmpi-devel devtoolset-10-gcc-c++.x86_64 && \
    yum clean all -y

# Get Python version
ARG PYTHON_VERSION

# Set default if needed. Available versions
# cp36-cp36m
# pp37-pypy37_pp73
# cp37-cp37m
# cp38-cp38
# cp39-cp39
# cp310-cp310
ENV PYTHON_VERSION=${PYTHON_VERSION:-cp37-cp37m}
ENV PYTHON=/opt/python/${PYTHON_VERSION}/bin/python

# Update path
ENV PATH=/usr/lib64/openmpi/bin:$PATH

# Update LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=/opt/python/${PYTHON_VERSION}/lib/:/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH

# Upgrade PIP
RUN $PYTHON -m pip install --no-cache --upgrade pip

# Install MPI4Py
RUN $PYTHON -m pip install --no-cache mpi4py

# Install JupyterLab
RUN $PYTHON -m pip install --no-cache jupyter notebook

# Copy requirements
COPY requirements.txt /tmp/

# Install requirements
RUN $PYTHON -m pip install --no-cache \
                      -r /tmp/requirements.txt \
                      scipy~=1.7 \
                      numpy~=1.21

# Remove requirements file
RUN rm /tmp/requirements.txt
