name: Pre-release actions

on:
  push:
    branches: [ pre-release-actions ]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build HybridQ container
        run: |
          docker-compose build --build-arg SKIP_PRE_CACHING=true --build-arg HYBRIDQ_DISABLE_CPP_CORE=true hybridq

      - name: Update documentation
        run: |
          docker run -v $(pwd)/docs:/opt/hybridq/docs --user root --rm hybridq bash -c '\
            curl -L https://github.com/jgm/pandoc/releases/download/2.14.2/pandoc-2.14.2-linux-amd64.tar.gz | tar xvzf - -C /opt/ && \
            export PATH=/opt/pandoc-2.13/bin/:$PATH && \
            yum install -y texlive-latex-bin \
                           texlive-xetex-bin \
                           texlive-metafont-bin \
                           texlive-cm \
                           texlive-iftex \
                           texlive-ifluatex \
                           texlive-euenc \
                           texlive-zapfding \
                           texlive-polyglossia \
                           texlive-lm-math \
                           texlive-dvipdfmx && \
            pip install pdoc3 && \
            cd /opt/hybridq && \
            bash scripts/generate_documentation.sh'

      - name: Add documentation to repository
        run: |
          git config --global user.email "github@action"
          git config --global user.name "GitHub Action"
          git fetch -p
          git checkout pre-release-actions
          git pull
          git add docs/*
          git commit -m "[Automated] Update documentation"
          git push -u origin pre-release-actions

  linux_wheel:
    needs: documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create packages for Linux
        run: |
          bash scripts/generate_packages.sh

      - name: Add package to repository
        run: |
          git config --global user.email "github@action"
          git config --global user.name "GitHub Action"
          git fetch -p
          git checkout pre-release-actions
          git pull
          git add packages/*.whl
          git commit -m "[Automated] Update wheels"
          git push -u origin pre-release-actions

  macos_wheel:
    needs: linux_wheel
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update PIP and install WHEEL
        run: |
          pip install -U wheel pip

      - name: Create package for MacOS
        run: |
          sed '/git+https/d' requirements.txt > /tmp/requirements.txt
          mv -f /tmp/requirements.txt requirements.txt
          CXX="clang++ -mmacosx-version-min=10.9" ARCH=core-avx2 pip wheel . -v --no-dependencies -w packages/
          mv packages/hybridq-*-py3-none-any.whl packages/hybridq-$(python setup.py --version)-py3-none-macosx_10_9_x86_64.whl

      - name: Add package to repository
        run: |
          git fetch -p
          git checkout pre-release-actions
          git pull
          git add packages/*.whl
          git commit -m "[Automated] Update wheels"
          git push -u origin pre-release-actions
