name: Python (cp37-cp37m) PyTest - simulation_4

on:
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull baseline for HybridQ
        run: |
          docker pull smandra/hybridq-baseline:cp37-cp37m
          docker tag smandra/hybridq-baseline:cp37-cp37m hybridq-baseline:latest

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build HybridQ container
        run: |
          docker-compose build --build-arg ARCH=x86-64 hybridq

      - name: Run tests
        run: |
          docker run --rm hybridq -c '$PYTHON -m pip install pytest-random-order && \
            $PYTHON -m pytest -sv --random-order -k 'simulation_4__' /opt/hybridq/tests/tests.py'
